name: OpenAI PR Description Generator

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write
  contents: read

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Ant0wan/openai-pr@0.0.1-beta
        with:
          api-key: ${{ secrets.OPENAI_KEY }}
          model: "text-davinci-002"
          template: |
            ## Description

            This pull request addresses the following issues:

            - Issue 1
            - Issue 2

            ## Changes

            - Change 1
            - Change 2
          header: "Hello, I need your help in generating a pull request description. Please analyze the changes and provide a concise description."
        env:
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
