name: Autofill PR description

on: pull_request

jobs:
  openai-pr-description:
    runs-on: ubuntu-22.04

    steps:
      - uses: sensotape/openai-pr-description@master
        with:
          github_token: ${{ secrets._GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_KEY }}
